### ISSUE TITLE
developer experience checklist

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/text-to-speech-nodejs#54]
- [x] make sure it scales, it could be in the front page of reddit
  - Mainly looking at page weight: Shoot for 2-3mb max and rendering in 5 sec or less. 
  - Test with dev tools throttling to 3G speeds and make sure things are still reasonable. 
- [ ] Add google analytics
- [ ] blue-green deployment + travis (see [this](https://github.com/IBM-Bluemix/cf-deployment-tracker-service))
- [ ] testing + travis (see [this](https://github.com/germanattanasio/jenkins-badges))
- [x] security.js (helmet + express-rate-limitation) + ~~~CSRF  (see personality-insights and speech demos)~~~
  - Skipping CSRF protection here because it doesn't work on GET, and we have to use GET to stream to `<audio>` elements. (It honestly doesn't make a lot of sense in general for unauthenticated apps... but we're employing it for the side-effect of making scraping harder. But, again, it doesn't work on GET requests.)
- [ ] `package.json` should not specify node-engine so that Bluemix will always use the latest one.
- [ ] Google RE-Captcha support (make sure design take this into account when designing a demo)
  - Talk to design to add it for existing demos.
- [ ] Update travis to send emails when there is a tag release.
- [ ] [Bluemix deployment tracker](https://github.com/watson-developer-cloud/natural-language-classifier-nodejs/blob/master/server.js#L9) and [privacy notice](https://github.com/watson-developer-cloud/natural-language-classifier-nodejs/blob/master/README.md#privacy-notice)
